version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-cabinet
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ADMIN_API_URL=http://host.docker.internal:8081
      - RENDER_SERVER_URL=http://render-server:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  render-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: render-server
    ports:
      - "4000:4000"