version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-cabinet
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./out:/app/out
    environment:
      - NODE_ENV=staging
      - ADMIN_API_URL=${ADMIN_API_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  render-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: render-server
    ports:
      - "4000:4000"